import type { CoursesV1Content } from "@/types/inner/courses-v1";
import innercoursescoursesThumbgrid31 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_1.svg";
import innercoursescoursesThumbgrid32 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_2.svg";
import innercoursescoursesThumbgrid33 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_3.svg";
import innercoursescoursesThumbgrid34 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_4.svg";
import innercoursescoursesThumbgrid35 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_5.svg";
import innercoursescoursesThumbgrid36 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_6.svg";
import innercoursescoursesThumbgrid37 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_7.svg";
import innercoursescoursesThumbgrid38 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_8.svg";
import innercoursescoursesThumbgrid39 from "@/public/assets/imgs/placeholder/courses-thumbgrid3_9.svg";
import innercoursescoursesClassicThumb11 from "@/public/assets/imgs/placeholder/courses-classic-thumb1_1.svg";
import innercoursescoursesClassicThumb12 from "@/public/assets/imgs/placeholder/courses-classic-thumb1_2.svg";
import innercoursescoursesClassicThumb13 from "@/public/assets/imgs/placeholder/courses-classic-thumb1_3.svg";
import innercoursescoursesClassicThumb14 from "@/public/assets/imgs/placeholder/courses-classic-thumb1_4.svg";
import innercoursescoursesClassicThumb15 from "@/public/assets/imgs/placeholder/courses-classic-thumb1_5.svg";

export const coursesV1Content: CoursesV1Content = {
  filter: {
    showingBefore: "Menampilkan",
    showingRange: "1-9",
    showingMid: "dari",
    showingTotal: "14",
    showingAfter: "Program",
    searchPlaceholder: "Cari program...",
    gridViewTitle: "Tampilan Grid",
    listViewTitle: "Tampilan Daftar",
    defaultTab: "list",
  },
  // The nine documented curriculum topics. TODO(route): the only detail
  // page is the Kelas Reguler one; per-program pages are PRD W8.
  grid: [
    {
      href: "/course-details-classic-v1",
      title: "Kepemimpinan Profetik",
      author: "Kelas Reguler",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid31,
      alt: "placeholder",
      clipId: "clip0_852_306115",
      price: "Gratis",
      lessons: "20 Sesi",
      courses: "2 Semester",
      students: "Terbuka umum",
    },
    {
      href: "/course-details-classic-v1",
      title: "Al-Qur'an dan Peradaban",
      author: "Kelas Reguler",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid32,
      alt: "placeholder",
      clipId: "clip0_852_306116",
      price: "Gratis",
      lessons: "20 Sesi",
      courses: "2 Semester",
      students: "Terbuka umum",
    },
    {
      href: "/course-details-classic-v1",
      title: "Worldview of Islam",
      author: "Kelas Reguler",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid33,
      alt: "placeholder",
      clipId: "clip0_852_306117",
      price: "Gratis",
      lessons: "20 Sesi",
      courses: "2 Semester",
      students: "Terbuka umum",
    },
    {
      href: "/course-details-classic-v1",
      title: "Filsafat Islam Klasik",
      author: "Kelas Reguler",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid34,
      alt: "placeholder",
      clipId: "clip0_852_306115",
      price: "Gratis",
      lessons: "20 Sesi",
      courses: "2 Semester",
      students: "Terbuka umum",
    },
    {
      href: "/course-details-classic-v1",
      title: "Tasawuf dan Masyarakat Jawa",
      author: "Kelas Reguler",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid35,
      alt: "placeholder",
      clipId: "clip0_852_306116",
      price: "Gratis",
      lessons: "20 Sesi",
      courses: "2 Semester",
      students: "Terbuka umum",
    },
    {
      href: "/course-details-classic-v1",
      title: "Islam dan Gender",
      author: "Kelas Reguler",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid36,
      alt: "placeholder",
      clipId: "clip0_852_306117",
      price: "Gratis",
      lessons: "20 Sesi",
      courses: "2 Semester",
      students: "Terbuka umum",
    },
    {
      href: "/course-details-classic-v1",
      title: "Fiqih Keluarga Milenial",
      author: "Kelas Reguler",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid37,
      alt: "placeholder",
      clipId: "clip0_852_306115",
      price: "Gratis",
      lessons: "20 Sesi",
      courses: "2 Semester",
      students: "Terbuka umum",
    },
    {
      href: "/course-details-classic-v1",
      title: "Filologi Sastra Islam",
      author: "Kelas Reguler",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid38,
      alt: "placeholder",
      clipId: "clip0_852_306116",
      price: "Gratis",
      lessons: "20 Sesi",
      courses: "2 Semester",
      students: "Terbuka umum",
    },
    {
      href: "/course-details-classic-v1",
      title: "Ghazwul Fikri",
      author: "Kursus Singkat",
      rating: "4.9/5",
      thumb: innercoursescoursesThumbgrid39,
      alt: "placeholder",
      clipId: "clip0_852_306117",
      price: "Gratis",
      lessons: "7 Sesi",
      courses: "1 Bulan",
      students: "Terbuka umum",
    },
  ],
  // The three program formats plus the two named online offerings and MARJAN.
  list: [
    {
      href: "/course-details-classic-v1",
      title: "Kelas Reguler — kajian pemikiran Islam dua semester",
      author: "Jakarta, Bandung, Yogyakarta, Bogor, Tangerang, Padang",
      rating: "4.9/5",
      thumb: innercoursescoursesClassicThumb11,
      alt: "placeholder",
      price: "Gratis",
      lessons: "20 Sesi",
      duration: "±7 Bulan",
      students: "Terbuka umum",
      level: "Semua jenjang",
    },
    {
      href: "/course-details-classic-v1",
      title: "Kursus Singkat untuk kelompok dan organisasi",
      author: "Seluruh cabang",
      rating: "4.9/5",
      thumb: innercoursescoursesClassicThumb12,
      alt: "placeholder",
      price: "Gratis",
      lessons: "7 Sesi",
      duration: "1 Bulan",
      students: "Kelompok",
      level: "Atas permintaan",
    },
    {
      href: "/course-details-classic-v1",
      title: "KOMIK — Kelas Online Pemikiran Islam",
      author: "Program Daring",
      rating: "4.9/5",
      thumb: innercoursescoursesClassicThumb13,
      alt: "placeholder",
      price: "Gratis",
      lessons: "Daring",
      duration: "Per angkatan",
      students: "Nasional",
      level: "Semua jenjang",
    },
    {
      href: "/course-details-classic-v1",
      title: "Tuesday's Special — sesi daring rutin",
      author: "Program Daring",
      rating: "4.9/5",
      thumb: innercoursescoursesClassicThumb14,
      alt: "placeholder",
      price: "Gratis",
      lessons: "Mingguan",
      duration: "Rutin",
      students: "Terbuka umum",
      level: "Semua jenjang",
    },
    {
      href: "/course-details-classic-v1",
      title: "MARJAN — Majelis Pemikiran di Kota Hujan",
      author: "SPI Bogor",
      rating: "4.9/5",
      thumb: innercoursescoursesClassicThumb15,
      alt: "placeholder",
      price: "Gratis",
      lessons: "20 Sesi",
      duration: "±7 Bulan",
      students: "Terbuka umum",
      level: "Semua jenjang",
    },
  ],
  pagination: [
    { label: "Sebelumnya", href: "#", direction: "prev" },
    { label: "1", href: "#", active: true },
    { label: "2", href: "#" },
    { label: "...", href: "#", ellipsis: true },
    { label: "3", href: "#" },
    { label: "5", href: "#" },
    { label: "Berikutnya", href: "#", direction: "next" },
  ],
};
